name: Build and deploy Python app to Azure Web App - lunchpicker

on:
  push:
    branches:
      - deploy-v2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn  # 必须添加

      - name: Package project
        run: |
          # 只打包必要文件（排除虚拟环境和无关文件）
          zip -r release.zip . -x "*.git*" "*.github*" "venv/*" "__pycache__/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'lunchpicker'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_246420633FA14B64BD603E167B134F80 }}
          package: release.zip
          # 关键修复：明确指定代码应部署到根目录
          target-path: /home/site/wwwroot
